#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright 2007-2013, Michael Boelen
# Copyright 2007-2021, CISOfy
#
# Website  : https://cisofy.com
# Blog     : http://linux-audit.com
# GitHub   : https://github.com/CISOfy/lynis
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# Category: Privilynis
#
#################################################################################
#
    InsertSection "PRIVLYINIS: Policy Checking Scripts "
#
#################################################################################



#################################################################################
# Test        : CVE-2022-0847
# Description : Check for Dirty Pipe vulnerability (CVE-2022-0847)



################################################################################

# Test        : CVE-2023-3269
# Description : Check for StackRot vulnerability (CVE-2023-3269)


#################################################################################

# Test        : CVE-2023-4911
# Description : Check for Looney Tunables vulnerability (CVE-2023-4911)



#################################################################################


# Wait for keypress (unless --quick is being used)
WaitForKeyPress

#
#================================================================================
# Lynis - Security Auditing and System Hardening for Linux and UNIX - https://cisofy.com
