#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright 2007-2013, Michael Boelen
# Copyright 2007-2021, CISOfy
#
# Website  : https://cisofy.com
# Blog     : http://linux-audit.com
# GitHub   : https://github.com/CISOfy/lynis
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# Category: Boot and services
#
#################################################################################
#
    InsertSection "PRIVLYINIS: Privilege Escalation CVE Detection"
#
#################################################################################
#
#    BOOT_LOADER="unknown"
#    BOOT_LOADER_FOUND=0
#    BOOT_LOADER_SEARCHED=0
#    GRUB_VERSION=0
#    if [ -z "${SERVICE_MANAGER}" ]; then
#        SERVICE_MANAGER="unknown"
#    fi
#################################################################################
#

# Test        : CVE-2022-0847
# Description : Check for Dirty Pipe vulnerability (CVE-2022-0847)
Register --test-no CVE-2022-0847 --weight L --network NO --category security --description "Check for privilege escalation vulnerability Dirty Pipe"

# Check if the test should be skipped
if [ "${SKIPTEST}" -eq 0 ]; then

    # Check if the kernel version is vulnerable to CVE-2022-0847
    VULNERABLE_KERNEL="5.8"
    KERNEL_VERSION=$(uname -r)
    if [ "$KERNEL_VERSION" = "$VULNERABLE_KERNEL" ]; then    
        Display --indent 4 --text "- CVE-2022-0847" --result WARNING --color RED
        LogText "Result: The system is vulnerable to Dirty Pipe (CVE-2022-0847)"
        ReportWarning "CVE-2022-0847" "The system is vulnerable to Dirty Pipe (CVE-2022-0847)"
    else
        Display --indent 4 --text "- CVE-2022-0847 " --result OK --color GREEN
        LogText "Result: The system is not vulnerable to Dirty Pipe (CVE-2022-0847)"
    fi
fi


#################################################################################

# Wait for keypress (unless --quick is being used)
WaitForKeyPress

#
#================================================================================
# Lynis - Security Auditing and System Hardening for Linux and UNIX - https://cisofy.com